/*
 * To change this license header, choose License Headers in Project Properties.
 * To changtemplatee this  file, choose Tools | Templates
 * and open the template in the editor.
 */
package matematicadisc;

import java.util.Scanner;
import javax.swing.JOptionPane;
import java.math.BigInteger;

/**
 *
 * @author Paulo
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        JogosdeAzar = new javax.swing.JButton();
        RodaDeCriancas = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JogosdeAzar.setText("Exercício 1");
        JogosdeAzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JogosdeAzarActionPerformed(evt);
            }
        });

        RodaDeCriancas.setText("Exercício 2");
        RodaDeCriancas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RodaDeCriancasActionPerformed(evt);
            }
        });

        jButton3.setText("Exercício 3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RodaDeCriancas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JogosdeAzar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JogosdeAzar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(RodaDeCriancas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JogosdeAzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JogosdeAzarActionPerformed
        Principios principio = new Principios();
        
        int vetor[] = new int[]{60,59,58,57,56,55};
        
        BigInteger mult = principio.PrincipioMultiplicativo(6, vetor);
        BigInteger result = mult.divide(principio.fatorial(6));
        String resolucao = new String("");
        
        for(int i=0;i<6;i++){
            resolucao+=(i==5? Integer.toString(vetor[i]): Integer.toString(vetor[i]) + " * ");
        }
        
        JOptionPane.showMessageDialog(null, "Descrição: \n\nAs chances de ganhar são de 1 em " + result + "\n\nResolução: \n(" + resolucao + ") / " + principio.fatorial(6), "Exercício 1 - Mega-Sena", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_JogosdeAzarActionPerformed

    private void RodaDeCriancasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RodaDeCriancasActionPerformed
        this.setVisible(false);
        new Exercício2().setVisible(true);
    }//GEN-LAST:event_RodaDeCriancasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JogosdeAzar;
    private javax.swing.JButton RodaDeCriancas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
